services:
  backend:
    build:
      context: ../MusicMe-Backend
    ports:
      - "3000:3000"
    env_file:
      - ../MusicMe-Backend/.env
    volumes:
      - ../MusicMe-Backend:/app  
      - /app/node_modules 
    command: ["npm", "run", "dev"]

  frontend:
    build:
      context: .
    ports:
      - "5173:5173" 
    depends_on:
      - backend
    env_file:
      - .env
    volumes:
      - .:/app  
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]
